"""added field engine

Revision ID: 54b79953d7b1
Revises: 8f97cd431741
Create Date: 2023-05-30 23:11:17.529519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b79953d7b1'
down_revision = '8f97cd431741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('r_d_s_monitor_cache', sa.Column('engine', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('r_d_s_monitor_cache', 'engine')
    # ### end Alembic commands ###
