"""db enhancements

Revision ID: 8f97cd431741
Revises: e7b79fd8894c
Create Date: 2023-05-05 18:10:35.138638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f97cd431741'
down_revision = 'e7b79fd8894c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
