"""alter size and new field pending_maintenance

Revision ID: e50a128c62c0
Revises: fef66fcee3f9
Create Date: 2023-04-15 17:25:57.160587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50a128c62c0'
down_revision = 'fef66fcee3f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('r_d_s_monitor_cache', sa.Column('pending_maintenance', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('r_d_s_monitor_cache', 'pending_maintenance')
    # ### end Alembic commands ###
