"""added model rds monitor cache

Revision ID: e7b79fd8894c
Revises: 9f37d15f1615
Create Date: 2023-02-25 16:15:35.946594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b79fd8894c'
down_revision = '9f37d15f1615'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_d_s_monitor_cache',
    sa.Column('maintenance_window', sa.String(length=36), nullable=True),
    sa.Column('backup_window', sa.String(length=36), nullable=True),
    sa.Column('automated_backups', sa.String(length=36), nullable=True),
    sa.Column('instance_class', sa.String(length=36), nullable=True),
    sa.Column('storage', sa.String(length=36), nullable=True),
    sa.Column('maximum_storage_threshold', sa.String(length=36), nullable=True),
    sa.Column('multi_az', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r_d_s_monitor_cache')
    # ### end Alembic commands ###
